### ISSUE TITLE
此插件会导致VSCode扩展宿主崩溃

### ISSUE THREAD

**Issue by sumneko** [sdttttt/vscode-bangumi#185]
可能和今天（4月1号）B站的番剧列表做了特殊处理有关

**Comment by LonelySteve** [comment]
可能和 VSCode 的稳定版更新有关系？今天上午更新 VSCode 到 1.55.0，然后发现这个崩溃提示，会导致一些扩展不可用，经过 bisect 发现此插件导致了这个问题，只能临时禁用了。

**Comment by sdttttt** [comment]
@sumneko, 感谢你的issue，我也注意到了，关闭BangumiOpen中的`EnableReminer`可以暂时解决这个问题。

我会调查这个原因的。

发件人: 最萌小汐
发送时间: 2021年4月1日 10:50
收件人: sdttttt/vscode-bangumi
抄送: Subscribed
主题: [sdttttt/vscode-bangumi] 此插件会导致VSCode扩展宿主崩溃 (#185)

可能和今天（4月1号）B站的番剧列表做了特殊处理有关

**Comment by sdttttt** [comment]
修复版本应该会在下午发布.

**Comment by sdttttt** [comment]
@sumneko, @LonelySteve, 很抱歉带来了麻烦, 已经更新到`2.2.5`了. (￣▽￣)"
